#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
echo "Holberton School" > /etc/nginx/html/index.html
echo "server {
listen 80;
listen [::]:80 default_server;
root   /etc/nginx/html;
index  index.html;
location /redirect_me {
return 301 https://www.facebook.com/hlahlobo.rakuoane.90;
}
}" > /etc/nginx/sites-available/default
service nginx restart
